drop database tsw_prog;
create database tsw_prog; 
USE tsw_prog;

CREATE TABLE PRODOTTI(
	id INT PRIMARY KEY,
    nome VARCHAR(15) NOT NULL,
    tipo ENUM('macchina','accessorio') NOT NULL,
    descrizione VARCHAR(500),
    data_rilascio VARCHAR(4),
    prezzo VARCHAR(15) NOT NULL,
	id_brand INT NOT NULL REFERENCES BRAND(id)
    ON UPDATE CASCADE ON DELETE CASCADE
); 

CREATE TABLE MEDIA(
	 percorso VARCHAR(100) PRIMARY KEY,
     id_prodotto INT NOT NULL REFERENCES PRODOTTI(id)
     ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE COLORI(
	 id int PRIMARY KEY,
     nome VARCHAR(15) NOT NULL
);

CREATE TABLE RUOTE(
	 id int PRIMARY KEY,
     tipo VARCHAR(15) NOT NULL
);

CREATE TABLE INTERNI (
    id INT PRIMARY KEY,
    tipo VARCHAR(15) NOT NULL
);

CREATE TABLE BRAND (
    id INT PRIMARY KEY,
    nome VARCHAR(15) NOT NULL,
    percorso_logo VARCHAR(100) NOT NULL
);

CREATE TABLE UTENTI (
    email VARCHAR(20) PRIMARY KEY,
	psw VARCHAR(15) NOT NULL,
    nome VARCHAR(15) NOT NULL,
    cognome VARCHAR(15) NOT NULL,
    telefono CHAR(12) NOT NULL,
	
    cap CHAR(5), 
    via VARCHAR(50),
    n_civ VARCHAR(3),
    
    numero_carta CHAR(16),
    data_scadenza_carta CHAR(5),
    cvv_carta CHAR(3)
);

CREATE TABLE ACQUISTI (
	data_acquisto DATE NOT NULL,
    tracciabilita VARCHAR(10),
    ruote VARCHAR(10),
    interni VARCHAR(10),
    colore VARCHAR(10),
    id_prodotto INT NOT NULL REFERENCES PRODOTTI (id)
    ON UPDATE CASCADE ON DELETE CASCADE,
	email_utenti VARCHAR(20) NOT NULL REFERENCES UTENTI(email)
    ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE PERSONALIZZAZIONE_RUOTE (
    id_prodotto INT NOT NULL REFERENCES PRODOTTI (id)
    ON UPDATE CASCADE ON DELETE CASCADE,
	id_ruote VARCHAR(20) NOT NULL REFERENCES RUOTE(id)
    ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE PERSONALIZZAZIONE_INTERNI (
    id_prodotto INT NOT NULL REFERENCES PRODOTTI (id)
    ON UPDATE CASCADE ON DELETE CASCADE,
	id_interni VARCHAR(20) NOT NULL REFERENCES INTERNI(id)
    ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE PERSONALIZZAZIONE_COLORE(
    id_prodotto INT NOT NULL REFERENCES PRODOTTI (id)
    ON UPDATE CASCADE ON DELETE CASCADE,
	id_colori VARCHAR(20) NOT NULL REFERENCES COLORI(id)
    ON UPDATE CASCADE ON DELETE CASCADE
);
